.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. bitsilver_qt test_bitsilver_qt
clean: FORCE
	$(MAKE) -C .. bitsilver_qt_clean test_bitsilver_qt_clean
check: FORCE
	$(MAKE) -C .. test_bitsilver_qt_check
bitsilver-qt bitsilver-qt.exe: FORCE
	 $(MAKE) -C .. bitsilver_qt
